<!DOCTYPE html>
<html>
    <head>
        <title><?php echo APP_COMPANY?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <link rel="apple-touch-icon" sizes="57x57" href="public/img/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="public/img/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="public/img/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="public/img/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="public/img/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="public/img/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="public/img/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="public/img/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="public/img/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="public/img/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="public/img/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="public/img/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="public/img/favicon/favicon-16x16.png">
        <link rel="manifest" href="public/img/favicon/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="public/img/favicon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">

        <!-- BOOTSTRAP -->
        <link rel="stylesheet" type="text/css" href="<?php echo $rutaLayout['css']; ?>bootstrap.min.css">
        <!-- SPINNERS -->
        <link href="<?php echo $rutaLayout['css']; ?>plugins/textSpinners/spinners.css" rel="stylesheet">
        <!-- JSTREE -->
        <link href="<?php echo $rutaLayout['css']; ?>plugins/jsTree/style.min.css" rel="stylesheet">
        <!-- JQUERY UI -->
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/js/jquery/jquery-ui.css">
        <!-- FONT AWESOME V.4.07 -->
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/external/font-awesome/css/font-awesome.min.css">
        <!-- ANIMATE -->
        <link href="<?php echo $rutaLayout['css']; ?>animate.css" rel="stylesheet" >
        <!-- ICHECK -->
        <link href="<?php echo $rutaLayout['css']; ?>plugins/iCheck/custom.css" rel="stylesheet">
        <!-- TAGSINPUT -->
        <link href="<?php echo $rutaLayout['css']; ?>plugins/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">
        
        <!-- SMART NOTIFICATION -->
        <link href="<?php echo BASE_URL; ?>public/js/notification/SmartNotification.css" rel="stylesheet" >
        <!-- STYLE -->
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/style.css">
        <!-- MENU -->
        <link href="<?php echo BASE_URL; ?>public/css/menu.css" rel="stylesheet" type="text/css" />
        
        <script src="<?php echo BASE_URL; ?>public/js/jquery/jquery.js"></script>
        <script src="<?php echo BASE_URL; ?>public/js/jquery/jquery-ui.js"></script>
        
        <!-- SCRIPT CORE -->
        <script src="<?php echo BASE_URL; ?>vendor/client/Ajax.js"></script>
        <script src="<?php echo BASE_URL; ?>vendor/client/Exe.js"></script>
        
    </head>
    <body class="pace-done skin-3 mini-navbar">