<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/js/jquery/jquery-ui.css">
        <!-- FONT AWESOME V.4.07 -->
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/external/font-awesome/css/font-awesome.min.css">
        
        <script src="<?php echo BASE_URL; ?>public/js/jquery/jquery.js"></script>
        <script src="<?php echo BASE_URL; ?>public/js/jquery/jquery-ui.js"></script>
        
        <!-- SCRIPT CORE -->
        <script src="<?php echo BASE_URL; ?>vendor/client/Ajax.js"></script>
        <script src="<?php echo BASE_URL; ?>vendor/client/Exe.js"></script>
        
    </head>
    <body>