
<link rel="stylesheet" type="text/css" href="<?php echo $rutaLayout['css']; ?>login.css">

<div class="main">


    <div class="container">
        <center>
            <div class="logo">LOGO
            </div>
            <div class="middle">
                <div id="login">

                    <form action="javascript:void(0);" method="get">

                        <fieldset class="clearfix">

                            <p ><span class="fa fa-user"></span><input type="text"  Placeholder="Username" required></p> <!-- JS because of IE support; better: placeholder="Username" -->
                            <p><span class="fa fa-lock"></span><input type="password"  Placeholder="Password" required></p> <!-- JS because of IE support; better: placeholder="Password" -->

                            <div>
                                <span style="width:60%; text-align:left;  display: inline-block;"><a class="small-text" href="#">¿Olvide mi contraseña?</a></span>
                                <span style="width:38%; text-align:right;  display: inline-block;">
                                    <button type="button"><i class="fa fa-unlock"></i> Entrar</button>
                                </span>
                            </div>

                        </fieldset>
                        <div class="clearfix"></div>
                    </form>

                    <div class="clearfix"></div>

                </div> <!-- end login -->


            </div>

        </center>
    </div>

</div>
