
<div id="wrapper">

    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0;background:#424242">
                <div class="navbar-header" style="margin-left: 10px;">
                    <nav id="main-nav" role="navigation">
                        <ul id="main-menu" class="sm sm-vertical sm-blue">
                            <li><h2><a href="javascript:;" class="has-submenu"><i class="fa fa-folder-open"></i> <span class="tr-language" data-tr="m_app"></span></a></h2>
                                <ul style="width: auto; display: none; top: auto; left: 0px; margin-left: 215px; margin-top: -49px; min-width: 10em; max-width: 20em;" id="sm-14973762961328103-8" role="group" aria-hidden="true" aria-labelledby="sm-14973762961328103-7" aria-expanded="false" class="sm-nowrap">
                                    <li><a href="#">Dummy item</a></li>
                                    <li><a href="#">Dummy item</a></li>
                                    <li><a href="#">Dummy item</a></li>
                                    <li><a href="#" class="has-submenu" id="sm-14973762961328103-9" aria-haspopup="true" aria-controls="sm-14973762961328103-10" aria-expanded="false"><span class="sub-arrow">+</span>more...</a>
                                        <ul style="width: 20em; min-width: 10em; display: none; max-width: 20em; top: auto; left: 0px; margin-left: 177px; margin-top: -446px;" id="sm-14973762961328103-10" role="group" aria-hidden="true" aria-labelledby="sm-14973762961328103-9" aria-expanded="false" class="">
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#" class="has-submenu" id="sm-14973762961328103-11" aria-haspopup="true" aria-controls="sm-14973762961328103-12" aria-expanded="false"><span class="sub-arrow">+</span>more...</a>
                                                <ul style="width: auto; min-width: 10em; display: none; max-width: 20em; top: auto; left: 0px; margin-left: 357px; margin-top: -49px;" id="sm-14973762961328103-12" role="group" aria-hidden="true" aria-labelledby="sm-14973762961328103-11" aria-expanded="false" class="sm-nowrap">
                                                    <li><a href="#">Dummy item</a></li>
                                                    <li><a href="#" class="current">A 'current' class item</a></li>
                                                    <li><a href="#">Dummy item</a></li>
                                                    <li><a href="#" class="has-submenu" id="sm-14973762961328103-13" aria-haspopup="true" aria-controls="sm-14973762961328103-14" aria-expanded="false"><span class="sub-arrow">+</span>more...</a>
                                                        <ul style="" id="sm-14973762961328103-14" role="group" aria-hidden="true" aria-labelledby="sm-14973762961328103-13" aria-expanded="false">
                                                            <li><a href="#">subMenusMinWidth</a></li>
                                                            <li><a href="#">10em</a></li>
                                                            <li><a href="#">forced.</a></li>
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Dummy item</a></li>
                                                    <li><a href="#">Dummy item</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">A pretty long text to test the default subMenusMaxWidth:20em setting for the sub menus</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">A pretty long text to test the default subMenusMaxWidth:20em setting for the sub menus</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">A pretty long text to test the default subMenusMaxWidth:20em setting for the sub menus</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">A pretty long text to test the default subMenusMaxWidth:20em setting for the sub menus</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">A pretty long text to test the default subMenusMaxWidth:20em setting for the sub menus</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                            <li><a href="#">Dummy item</a></li>
                                        </ul><span class="scroll-up" style="top: auto; left: 0px; margin-left: 178px; width: 358px; z-index: 10004; margin-top: -446px; visibility: hidden; display: none;"><span class="scroll-up-arrow"></span></span><span class="scroll-down" style="display: none; top: auto; left: 0px; margin-left: 178px; width: 358px; z-index: 10004; margin-top: 138px; visibility: hidden;"><span class="scroll-down-arrow"></span></span>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                </div>
                <div class="navbar-header navbar-form-custom" style="margin-left: 10px;">
                    <input type="text" class="form-control tr-language-ph search_menu" data-tr="buscar_menu"/>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <div class=" profile-element" style="display: block;float: left"> 
                            
                            <span data-toggle="dropdown" class="dropdown-toggle" href="#" style="display: inline-block;cursor: pointer">
                                <span class="text-muted text-xs block" style="color:#fff"><?php echo Obj()->Vendor->Session->get('sys_defaultNameRol') ?> <b class="caret"></b></span> 
                            </span>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs" >
                                <?php
                                $ocr = '';
                                $cssrol = '';
                                foreach (Obj()->Vendor->Session->get('sys_roles') as $key => $value):
                                    $ocr = ($value['nrol'] != Obj()->Vendor->Session->get('sys_defaultNameRol')) ? 'alert("aqui funcion para cambiar rol")' : '';
                                    $cssrol = ($value['nrol'] != Obj()->Vendor->Session->get('sys_defaultNameRol')) ? 'arol' : '';
                                    ?>
                                    <?php if ($value['nrol'] != Obj()->Vendor->Session->get('sys_defaultNameRol')): ?>
                                        <li><a href="javascript:;" class="<?php echo $cssrol ?>"><i class="fa fa-bars"></i> <?php echo $value['nrol'] ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                            <script>
                                $('.arol').click(function () {
                                    <?php echo $ocr ?>
                                });
                            </script>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-envelope" style="color:#fff"></i>  <span class="label label-warning">16</span>
                        </a>
                        <ul class="dropdown-menu dropdown-messages">
                            <li>
                                <div class="dropdown-messages-box">
                                    <a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="img/a7.jpg">
                                    </a>
                                    <div class="media-body">
                                        <small class="pull-right">46h ago</small>
                                        <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                        <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box">
                                    <a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="img/a4.jpg">
                                    </a>
                                    <div class="media-body ">
                                        <small class="pull-right text-navy">5h ago</small>
                                        <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                        <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box">
                                    <a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="img/profile.jpg">
                                    </a>
                                    <div class="media-body ">
                                        <small class="pull-right">23h ago</small>
                                        <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                        <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                    <a href="mailbox.html">
                                        <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell" style="color:#fff"></i>  <span class="label label-primary">8</span>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="mailbox.html">
                                    <div>
                                        <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="profile.html">
                                    <div>
                                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                        <span class="pull-right text-muted small">12 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="grid_options.html">
                                    <div>
                                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                    <a href="notifications.html">
                                        <strong>See All Alerts</strong>
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="info_user">
                        <span data-toggle="dropdown" class="dropdown-toggle">
                            <img alt="image" class="img-circle" src="<?php echo BASE_URL; ?>public/img/profile_small.jpg" style="margin-top: -5px;cursor: pointer" title="<?php echo Obj()->Vendor->Session->get('sys_nameUser') ?>"/>
                        </span>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs" >
                            <li><a href="javascript:;" ><i class="fa fa-lock"></i> <span class="tr-language" data-tr="cambia_pass"></span></a></li>
                            <li><a href="javascript:;" onclick="Exe.InitDom.logOut();"><i class="fa fa-sign-out"></i> <span class="tr-language" data-tr="out"></span></a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>


    </div>




</div>