<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>public/css/login.css">
<div  class="main">
    <div class="container">
        <center id="main">
            <div class="logo"></div>
            <div class="middle">
                <div id="login">
                    <form id="formLogin" name="formLogin" onsubmit="return false;">
                        <fieldset class="clearfix">
                            <p>
                                <span class="fa fa-user spor"></span><input type="text" class="tr-language-ph" data-trph="user" id="txtUser" name="txtUser">
                            </p> 
                            <p>
                                <span class="fa fa-lock spor"></span><input type="password" class="tr-language-ph" data-trph="pass" id="txtClave" name="txtClave">
                            </p> 
                            <div>
                                <span style="width:62%; text-align:left;  display: inline-block;">
                                    <a class="small-text tr-language" href="javascript:;" data-tr="forgot_pass"></a>
                                </span>
                                <span style="width:36%; text-align:right;  display: inline-block;">
                                    <button id="btn_entrar" type="submit" class="ui-button ui-widget ui-corner-all"><i class="fa fa-unlock"></i> <span class="tr-language" data-tr="btn_entrar"></span></button>
                                </span>
                            </div>
                        </fieldset>
                        <div class="clearfix"></div>
                    </form>
                    <div class="clearfix"></div>
                </div> <!-- end login -->
            </div>
            <div class="foot tr-language" data-tr="copy_right"></div>
        </center>
    </div>
</div>
